In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os
os.chdir("/content/drive/My Drive/ML Practicals/data/")

In [ ]:
!jupyter nbconvert --to html ../Lecture_Preprocessing_2.ipynb


[NbConvertApp] Converting notebook ../Lecture_Preprocessing_2.ipynb to html
[NbConvertApp] Writing 709731 bytes to ../Lecture_Preprocessing_2.html


#Pre Processing includes many steps

- Domain Knowledge
- Data Cleaning
  - Handling Missing Values
  - Handling outliers
- Data Transformation
  - Feature Scaling
  - Encoding Categorical Data
- Feature Engineering
  - Creating New Features
  - Dimensionality Reduction
- Handling Imbalanced Data
- Handling Time Series Data
- Splitting Data

In [5]:
import pandas as pd
df = pd.read_csv('customer.csv')

In [6]:
df.sample(5)

age  gender   review education purchased
43   27    Male     Poor        PG        No
11   74    Male     Good        UG       Yes
42   30  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
44   77  Female  Average        UG        No

In [7]:
df = df.iloc[:,2:]
df.head()


review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [8]:
X = df.iloc[:,0:2]
y= df.iloc[:,-1]
X

review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [9]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])


In [10]:
oe.fit(X)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X = oe.transform(X)

In [12]:
X

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()
le.fit(y)


LabelEncoder()

In [15]:
y = le.transform(y)

In [16]:
y

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Sample data with multiple classes in the target variable (y)
y = ['red', 'blue', 'green', 'red', 'green', 'blue', 'red']

# Create a LabelEncoder instance
le = LabelEncoder()

# Fit and transform the labels
y_encoded = le.fit_transform(y)

print("Original labels:", y)
print("Encoded labels:", y_encoded)


## One Hot Encoding

In [ ]:
df = pd.read_csv('cars.csv')

In [ ]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['owner'].value_counts()


First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: owner, dtype: int64

In [ ]:
df['brand'].value_counts()


Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

In [ ]:
df['fuel'].value_counts()


Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: fuel, dtype: int64

#OHE using pandas

In [ ]:
temp = pd.get_dummies(df,columns=['fuel','owner'])
temp


brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

#N-1 OHE

In [ ]:
temp = pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)
temp.sample(5)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
2972  Maruti      44000          94500            0         0            1   
5095  Maruti      69779         600000            0         0            1   
2787    Ford     150000         325000            1         0            0   
4880     BMW      60000        1000000            1         0            0   
8008  Maruti      40000         382000            0         0            1   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
2972                           0                   0                     0   
5095                           0                   0                     0   
2787                           0                   0                     0   
4880                           0                   0                     0   
8008                           0                   0                     0   

      owner_Third Owner  
2972                  0  
5095                  0  
2787                  0  
4880                  0  
8008                  0

In [ ]:
selected_rows = temp[(temp['fuel_Diesel'] == 0) & (temp['fuel_LPG'] == 0) & (temp['fuel_Petrol'] == 0)]
selected_rows.head(5)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
35    Maruti      10000         330000            0         0            0   
203   Maruti      50000         360000            0         0            0   
402   Maruti      35000         409999            0         0            0   
866   Maruti      60000         165000            0         0            0   
1225  Maruti      10000         450000            0         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
35                             0                   1                     0   
203                            0                   0                     0   
402                            0                   0                     0   
866                            0                   1                     0   
1225                           0                   0                     0   

      owner_Third Owner  
35                    0  
203                   0  
402                   0  
866                   0  
1225                  0

#OHE using SKLEARN

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32)


In [ ]:
temp = ohe.fit_transform(df[['fuel','owner']])
temp

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

#Use of Column Transformer

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df = pd.read_csv('covid.csv')

In [ ]:
df.sample(10)

age  gender  fever   cough       city has_covid
51   11  Female  100.0  Strong    Kolkata       Yes
0    60    Male  103.0    Mild    Kolkata        No
72   83  Female  101.0    Mild    Kolkata        No
5    84  Female    NaN    Mild  Bangalore       Yes
80   14  Female   99.0    Mild     Mumbai       Yes
45   72    Male   99.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
68   54  Female  104.0  Strong    Kolkata        No
34   74    Male  102.0    Mild     Mumbai       Yes
85   16  Female  103.0    Mild  Bangalore       Yes

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
si = SimpleImputer()
df_fever = si.fit_transform(df[['fever']])
df_fever

array([[103.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.84444444],
       [101.        ],
       [100.84444444],
       [100.        ],
       [101.        ],
       [100.84444444],
       [ 98.        ],
       [ 99.        ],
       [102.        ],
       [104.        ],
       [103.        ],
       [103.        ],
       [ 98.        ],
       [ 98.        ],
       [100.84444444],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [100.84444444],
       [100.        ],
       [102.        ],
       [104.        ],
       [100.84444444],
       [101.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [102.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [102.        ],
       [100.84444444],
       [100.        ],
       [ 99

In [ ]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
df_cough = oe.fit_transform(df[['cough']])
df_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],

In [ ]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse=False)
df_gender_city = ohe.fit_transform(df[['gender','city']])
df_gender_city

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],


In [ ]:
df_age = df.drop(columns=['gender','fever','cough','city']).values

df_transformed = np.concatenate((df_age,df_fever,df_gender_city,df_cough),axis=1)
df_transformed.shape

(100, 8)

#Let us use efficient way

In [ ]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [ ]:
transformer.fit_transform(df).shape


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(100, 8)